# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171009_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypage',
            options={'verbose_name': '\u5206\u7c7b\u9875\u9762'},
        ),
        migrations.AlterModelOptions(
            name='gallerypage',
            options={'verbose_name': '\u56fe\u7247\u9875\u9762'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '\u4e3b\u9875'},
        ),
        migrations.AlterModelOptions(
            name='simplepage',
            options={'verbose_name': '\u7b80\u5355\u9875\u9762'},
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
