# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_simplepage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
